
  CREATE TABLE "TJOEUNIT"."REPLE" 
   (	"REPLEIDX" NUMBER(*,0), 
	"ORIGINIDX" NUMBER(*,0) NOT NULL ENABLE, 
	"MASTERID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"REPLEID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"REPLE" VARCHAR2(500 BYTE), 
	"SEQ" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"WRITEDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"REPLEIP" CHAR(15 BYTE), 
	"FIX" VARCHAR2(3 BYTE) DEFAULT 'N', 
	"REPLENICKNAME" VARCHAR2(30 BYTE), 
	"REPLEGENDER" VARCHAR2(10 BYTE), 
	"REPLEAGE" NUMBER(*,0), 
	"REPLELIMITNUM" NUMBER(*,0), 
	"REPLECOUNTNUM" NUMBER(*,0), 
	 CONSTRAINT "REPLE_PK" PRIMARY KEY ("REPLEIDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


--������ ���� �� ����

delete from reple;
drop sequence reple_idx_seq;
create sequence reple_idx_seq;
commit;

select * from reple;

select * from join where id = 'sdsa1';
